services:
  - type: web
    name: wrtpros
    env: node
    buildCommand: ""
    startCommand: node server.js
    envVars:
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_FROM_NUMBER
        sync: false
      - key: CONTACT_TO_NUMBER
        sync: false
